"""empty message

Revision ID: bf89edfe0cdc
Revises: f22a6f498207
Create Date: 2022-08-04 21:56:49.138148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf89edfe0cdc'
down_revision = 'f22a6f498207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'content',
               existing_type=sa.VARCHAR(length=280),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'content',
               existing_type=sa.VARCHAR(length=280),
               nullable=False)
    # ### end Alembic commands ###
