"""empty message

Revision ID: f22a6f498207
Revises: ffdc0a98111c
Create Date: 2022-08-02 10:24:56.341414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f22a6f498207'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jokes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=280), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joke_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=280), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['joke_id'], ['jokes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('display_name', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('bio', sa.String(length=160), nullable=True))
    op.add_column('users', sa.Column('header', sa.String(), nullable=True))
    op.add_column('users', sa.Column('prof_pic_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('birthday', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('joined', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'users', ['display_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'joined')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'location')
    op.drop_column('users', 'prof_pic_url')
    op.drop_column('users', 'header')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'display_name')
    op.drop_table('comments')
    op.drop_table('jokes')
    # ### end Alembic commands ###
